spring:
  profiles:
    active: "local"
  application:
    name: authorization-server
  messages:
    basename: i18n/messages
    encoding: UTF-8
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8991
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
