spring:
  profiles:
    active: "local"
  application:
    name: authorization-server
  messages:
    basename: i18n/messages
    encoding: UTF-8
  config:
    import: optional:configserver:http://localhost:8888
  sleuth:
    sampler:
      probability: 1.0 #trace all request
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
server:
  port: 8991
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'